import { Inter } from "next/font/google"
import TransitionProvider from "./components/transitionProvider"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Raihana Portfolio App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Protest+Guerrilla&family=Tilt+Prism:YROT@9&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <TransitionProvider items={children} />
      </body>
    </html>
  )
}
